//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akka.Streams.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akka.Streams.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Actor must be ActorPublisher 的本地化字符串。
        /// </summary>
        internal static string Argument_Actor_must_be_publisher {
            get {
                return ResourceManager.GetString("Argument_Actor_must_be_publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Balance must have one or more output ports 的本地化字符串。
        /// </summary>
        internal static string Argument_Balance_must_have_outputports {
            get {
                return ResourceManager.GetString("Argument_Balance_must_have_outputports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Broadcast must have one or more output ports 的本地化字符串。
        /// </summary>
        internal static string Argument_Broadcast_must_have_outputports {
            get {
                return ResourceManager.GetString("Argument_Broadcast_must_have_outputports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer must be greater than zero 的本地化字符串。
        /// </summary>
        internal static string Argument_Buffer_must_be_g_t_zero {
            get {
                return ResourceManager.GetString("Argument_Buffer_must_be_g_t_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer Count must be power of two 的本地化字符串。
        /// </summary>
        internal static string Argument_BufferCount_PowerofTwo {
            get {
                return ResourceManager.GetString("Argument_BufferCount_PowerofTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer size cannot be zero 的本地化字符串。
        /// </summary>
        internal static string Argument_Buffersize_zero {
            get {
                return ResourceManager.GetString("Argument_Buffersize_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Concat must have more than 1 input port 的本地化字符串。
        /// </summary>
        internal static string Argument_Concat_must_have_inputports {
            get {
                return ResourceManager.GetString("Argument_Concat_must_have_inputports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExitMaterializationContext with empty stack 的本地化字符串。
        /// </summary>
        internal static string Argument_EMC_with_empty_stack {
            get {
                return ResourceManager.GetString("Argument_EMC_with_empty_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 empty iterator 的本地化字符串。
        /// </summary>
        internal static string Argument_empty_iterator {
            get {
                return ResourceManager.GetString("Argument_empty_iterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tried to enqueue without waiting for any demand 的本地化字符串。
        /// </summary>
        internal static string Argument_FanOut_IdToEn {
            get {
                return ResourceManager.GetString("Argument_FanOut_IdToEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length field length must be 1,2,3 or 4 的本地化字符串。
        /// </summary>
        internal static string Argument_Framing_FieldLength {
            get {
                return ResourceManager.GetString("Argument_Framing_FieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;inlets&apos; and &apos;inletOwners&apos; must have the same length. 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphAssembly_IO {
            get {
                return ResourceManager.GetString("Argument_GraphAssembly_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;inletOwners&apos; and &apos;outlets&apos; must have the same length. 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphAssembly_O {
            get {
                return ResourceManager.GetString("Argument_GraphAssembly_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;outlets&apos; and &apos;outletOwners&apos; must have the same length. 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphAssembly_OO {
            get {
                return ResourceManager.GetString("Argument_GraphAssembly_OO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot get element from already empty input port 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphStage_Grab {
            get {
                return ResourceManager.GetString("Argument_GraphStage_Grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot pull a closed port 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphStage_PullC {
            get {
                return ResourceManager.GetString("Argument_GraphStage_PullC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read negative number of elements 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphStage_ReadMany {
            get {
                return ResourceManager.GetString("Argument_GraphStage_ReadMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot pull port twice 的本地化字符串。
        /// </summary>
        internal static string Argument_GraphStage_Twice {
            get {
                return ResourceManager.GetString("Argument_GraphStage_Twice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer size larger then 4095 is not allowed 的本地化字符串。
        /// </summary>
        internal static string Argument_Hub_buffer_4095 {
            get {
                return ResourceManager.GetString("Argument_Hub_buffer_4095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer size must be positive 的本地化字符串。
        /// </summary>
        internal static string Argument_Hub_buffer_positive {
            get {
                return ResourceManager.GetString("Argument_Hub_buffer_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer size must be a power of two 的本地化字符串。
        /// </summary>
        internal static string Argument_Hub_buffer_power_two {
            get {
                return ResourceManager.GetString("Argument_Hub_buffer_power_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase step must be positive 的本地化字符串。
        /// </summary>
        internal static string Argument_Increase_step_non_positive {
            get {
                return ResourceManager.GetString("Argument_Increase_step_non_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inlet name must be defined 的本地化字符串。
        /// </summary>
        internal static string Argument_Inletname_IsNull {
            get {
                return ResourceManager.GetString("Argument_Inletname_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interleave input ports count must be greater than 1 的本地化字符串。
        /// </summary>
        internal static string Argument_InputPorts_NeedGreaterThanOne {
            get {
                return ResourceManager.GetString("Argument_InputPorts_NeedGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max delay must be bigger than initial delay 的本地化字符串。
        /// </summary>
        internal static string Argument_Maxdelay_less_than_initial {
            get {
                return ResourceManager.GetString("Argument_Maxdelay_less_than_initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Throttle maximumBurst must be &gt; 0 in Enforcing mode 的本地化字符串。
        /// </summary>
        internal static string Argument_MaximumBurst_GreaterThanZero {
            get {
                return ResourceManager.GetString("Argument_MaximumBurst_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Merge must have one or more input ports 的本地化字符串。
        /// </summary>
        internal static string Argument_Merge_must_have_input_ports {
            get {
                return ResourceManager.GetString("Argument_Merge_must_have_input_ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A MergePreferred must have at least one secondary port 的本地化字符串。
        /// </summary>
        internal static string Argument_MergePreferred_least_one {
            get {
                return ResourceManager.GetString("Argument_MergePreferred_least_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A module cannot be added to itself. You should pass a separate instance to compose(). 的本地化字符串。
        /// </summary>
        internal static string Argument_module_cannot_be_added_to_itself {
            get {
                return ResourceManager.GetString("Argument_module_cannot_be_added_to_itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more inlets free on junction 的本地化字符串。
        /// </summary>
        internal static string Argument_Nomore_inlets_free_jun {
            get {
                return ResourceManager.GetString("Argument_Nomore_inlets_free_jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more inlets on junction 的本地化字符串。
        /// </summary>
        internal static string Argument_Nomore_inlets_jun {
            get {
                return ResourceManager.GetString("Argument_Nomore_inlets_jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more outlets on junction 的本地化字符串。
        /// </summary>
        internal static string Argument_Nomore_outlets_jun {
            get {
                return ResourceManager.GetString("Argument_Nomore_outlets_jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 offset + count must be smaller or equal to the array length 的本地化字符串。
        /// </summary>
        internal static string Argument_Offset_Count_Length {
            get {
                return ResourceManager.GetString("Argument_Offset_Count_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PushMaterializationSource without context 的本地化字符串。
        /// </summary>
        internal static string Argument_PMS_without_context {
            get {
                return ResourceManager.GetString("Argument_PMS_without_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priorities should be positive integers 的本地化字符串。
        /// </summary>
        internal static string Argument_Priorities_be_positive_int {
            get {
                return ResourceManager.GetString("Argument_Priorities_be_positive_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rates larger than 1 unit / tick are not supported 的本地化字符串。
        /// </summary>
        internal static string Argument_Rates_NotSupported {
            get {
                return ResourceManager.GetString("Argument_Rates_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CombinedModule requires shape with same ports to replace 的本地化字符串。
        /// </summary>
        internal static string Argument_ReplaceShape_CombinedModule {
            get {
                return ResourceManager.GetString("Argument_ReplaceShape_CombinedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopiedModule requires shape with same ports to replace 的本地化字符串。
        /// </summary>
        internal static string Argument_ReplaceShape_CopiedModule {
            get {
                return ResourceManager.GetString("Argument_ReplaceShape_CopiedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FusedModule requires shape with the same ports as existing one 的本地化字符串。
        /// </summary>
        internal static string Argument_ReplaceShape_FusedModule {
            get {
                return ResourceManager.GetString("Argument_ReplaceShape_FusedModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StructuralInfoModule requires shape with same ports to replace 的本地化字符串。
        /// </summary>
        internal static string Argument_ReplaceShape_StructuralInfoModule {
            get {
                return ResourceManager.GetString("Argument_ReplaceShape_StructuralInfoModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 number of retries must be non-negative or equal to -1 的本地化字符串。
        /// </summary>
        internal static string Argument_retries_non_negative {
            get {
                return ResourceManager.GetString("Argument_retries_non_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 initialSize must be a power of 2 that is &gt; 0 and &lt;= maxSize 的本地化字符串。
        /// </summary>
        internal static string Argument_RMRRB_initialSize {
            get {
                return ResourceManager.GetString("Argument_RMRRB_initialSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 maxSize must be a power of 2 that is &gt; 0 and &lt; Int.MaxValue/2 的本地化字符串。
        /// </summary>
        internal static string Argument_RMRRB_maxSize {
            get {
                return ResourceManager.GetString("Argument_RMRRB_maxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max step for a random sampling must &gt; 0 的本地化字符串。
        /// </summary>
        internal static string Argument_Sample_Max_step {
            get {
                return ResourceManager.GetString("Argument_Sample_Max_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interleave segment size must be greater than 0 的本地化字符串。
        /// </summary>
        internal static string Argument_SegmentSize_NeedGreaterThanZero {
            get {
                return ResourceManager.GetString("Argument_SegmentSize_NeedGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An existing submodule cannot be added again. All contained modules must be unique. 的本地化字符串。
        /// </summary>
        internal static string Argument_submodule_cannot_be_added_again {
            get {
                return ResourceManager.GetString("Argument_submodule_cannot_be_added_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription cannot be null 的本地化字符串。
        /// </summary>
        internal static string Argument_Subscription_IsNull {
            get {
                return ResourceManager.GetString("Argument_Subscription_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 akka.stream.materializer.subscribtion-timeout.mode was not defined or has invalid value. Valid values are: no, off, false, noop, warn, cancel 的本地化字符串。
        /// </summary>
        internal static string Argument_subscription_timeout {
            get {
                return ResourceManager.GetString("Argument_subscription_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Throttle per timeout must not be zero 的本地化字符串。
        /// </summary>
        internal static string Argument_ThrottlePer_NonZero {
            get {
                return ResourceManager.GetString("Argument_ThrottlePer_NonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout must be non-zero 的本地化字符串。
        /// </summary>
        internal static string Argument_Timeout_NeedNonZero {
            get {
                return ResourceManager.GetString("Argument_Timeout_NeedNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowShape expected non-null inlet 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_FlowShape_Inlet {
            get {
                return ResourceManager.GetString("ArgumentNull_FlowShape_Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowShape expected non-null outlet 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_FlowShape_Outlet {
            get {
                return ResourceManager.GetString("ArgumentNull_FlowShape_Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GraphStageLogic onPull handler must be provided 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_GraphStageLogic_OnPull {
            get {
                return ResourceManager.GetString("ArgumentNull_GraphStageLogic_OnPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GraphStageLogic onPush handler must be provided 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_GraphStageLogic_OnPush {
            get {
                return ResourceManager.GetString("ArgumentNull_GraphStageLogic_OnPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IActorRefFactory must be defined 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_IActorRefFactoryIsNull {
            get {
                return ResourceManager.GetString("ArgumentNull_IActorRefFactoryIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_KeyIsNull {
            get {
                return ResourceManager.GetString("ArgumentNull_KeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name attribute cannot be empty 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_NameAttrIsNull {
            get {
                return ResourceManager.GetString("ArgumentNull_NameAttrIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnError has no cause defined 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_OnErrorRequire {
            get {
                return ResourceManager.GetString("ArgumentNull_OnErrorRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnNext requires provided element not to be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_OnNextRequire {
            get {
                return ResourceManager.GetString("ArgumentNull_OnNextRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnSubscribe requires subscription to be defined 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_OnSubscribeRequire {
            get {
                return ResourceManager.GetString("ArgumentNull_OnSubscribeRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActorSubscriberImpl requires actor impl to be defined 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_RequireActorImpl {
            get {
                return ResourceManager.GetString("ArgumentNull_RequireActorImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActorPublisherImpl requires IActorRef to be defined 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_RequiresIActorRef {
            get {
                return ResourceManager.GetString("ArgumentNull_RequiresIActorRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActorPublisherSubscription requires IActorRef to be defined 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_RequiresIActorRef_PS {
            get {
                return ResourceManager.GetString("ArgumentNull_RequiresIActorRef_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SinkShape expected non-null inlet 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_SinkShape_Inlet {
            get {
                return ResourceManager.GetString("ArgumentNull_SinkShape_Inlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscriber must not be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_SubscriberIsNull {
            get {
                return ResourceManager.GetString("ArgumentNull_SubscriberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer key cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_TimerKeyIsNull {
            get {
                return ResourceManager.GetString("ArgumentNull_TimerKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This actor cannot be restarted 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Actor_Cannot_Restart {
            get {
                return ResourceManager.GetString("IllegalState_Actor_Cannot_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already emitting a state 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Al_emitting_state {
            get {
                return ResourceManager.GetString("IllegalState_Al_emitting_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already in emitting state 的本地化字符串。
        /// </summary>
        internal static string IllegalState_AlIn_emitting_state {
            get {
                return ResourceManager.GetString("IllegalState_AlIn_emitting_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempted to call Materialize() after the ActorMaterializer has been shut down. 的本地化字符串。
        /// </summary>
        internal static string IllegalState_call_materialize {
            get {
                return ResourceManager.GetString("IllegalState_call_materialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Called Apply on NotReached 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Call_NotReached {
            get {
                return ResourceManager.GetString("IllegalState_Call_NotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descend returned empty result from CopiedModule 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Descend_EmptyResult {
            get {
                return ResourceManager.GetString("IllegalState_Descend_EmptyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First message must be Initialized notification 的本地化字符串。
        /// </summary>
        internal static string IllegalState_first_msg_init {
            get {
                return ResourceManager.GetString("IllegalState_first_msg_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot materialize an incoming connection Flow twice. 的本地化字符串。
        /// </summary>
        internal static string IllegalState_incoming_conn {
            get {
                return ResourceManager.GetString("IllegalState_incoming_conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 message &apos;Initialized&apos; must come first 的本地化字符串。
        /// </summary>
        internal static string IllegalState_init_mus_first {
            get {
                return ResourceManager.GetString("IllegalState_init_mus_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input buffer overrun 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Inputbuffer_Overrun {
            get {
                return ResourceManager.GetString("IllegalState_Inputbuffer_Overrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 internal error 的本地化字符串。
        /// </summary>
        internal static string IllegalState_internal_err {
            get {
                return ResourceManager.GetString("IllegalState_internal_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not yet initialized: only SetHandler is allowed in GraphStageLogic constructor 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Not_yet_init {
            get {
                return ResourceManager.GetString("IllegalState_Not_yet_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnComplete must not be called after OnError 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnComplete_AfterE {
            get {
                return ResourceManager.GetString("IllegalState_OnComplete_AfterE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnComplete must only be called once 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnComplete_Once {
            get {
                return ResourceManager.GetString("IllegalState_OnComplete_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnError must not be called after OnComplete 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnError_AfterC {
            get {
                return ResourceManager.GetString("IllegalState_OnError_AfterC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnError must only be called once 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnError_Once {
            get {
                return ResourceManager.GetString("IllegalState_OnError_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnNext must not be called after OnComplete 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnNext_AfterC {
            get {
                return ResourceManager.GetString("IllegalState_OnNext_AfterC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnNext must not be called after OnError 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnNext_AfterE {
            get {
                return ResourceManager.GetString("IllegalState_OnNext_AfterE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnNext is not allowed when the stream has not requested elements, total demand was 0 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnNext_NotAllowed {
            get {
                return ResourceManager.GetString("IllegalState_OnNext_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnPull with empty enumerator is not expected in emitting state 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnPull_empty_enumerator {
            get {
                return ResourceManager.GetString("IllegalState_OnPull_empty_enumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnPush is not allowed in emitting state 的本地化字符串。
        /// </summary>
        internal static string IllegalState_OnPush_not_allowed {
            get {
                return ResourceManager.GetString("IllegalState_OnPush_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output buffer overflow 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Output_buf_overflow {
            get {
                return ResourceManager.GetString("IllegalState_Output_buf_overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The action of completed phase must never be executed 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Pump_CompletedPhaseNeverExec {
            get {
                return ResourceManager.GetString("IllegalState_Pump_CompletedPhaseNeverExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pump has not been initialized with a phase 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Pump_NonInitialized {
            get {
                return ResourceManager.GetString("IllegalState_Pump_NonInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PushToDownStream(...) after CompleteDownstream() or AbortDownstream(...) 的本地化字符串。
        /// </summary>
        internal static string IllegalState_PushToDownStream_A {
            get {
                return ResourceManager.GetString("IllegalState_PushToDownStream_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal queue must never contain a null 的本地化字符串。
        /// </summary>
        internal static string IllegalState_queue_never_null {
            get {
                return ResourceManager.GetString("IllegalState_queue_never_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s illegal to try to signal OnError with a spec violation 的本地化字符串。
        /// </summary>
        internal static string IllegalState_signal_err_spec {
            get {
                return ResourceManager.GetString("IllegalState_signal_err_spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnSubscribe called after OnError or OnComplete 的本地化字符串。
        /// </summary>
        internal static string IllegalState_sub_called_after_err {
            get {
                return ResourceManager.GetString("IllegalState_sub_called_after_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscriber threw exception, this is in violation of rule 2:13 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Sub_throw_ex {
            get {
                return ResourceManager.GetString("IllegalState_Sub_throw_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Substream Source cannot be materialized more than once 的本地化字符串。
        /// </summary>
        internal static string IllegalState_Substream_Source {
            get {
                return ResourceManager.GetString("IllegalState_Substream_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tried to dequeue without waiting for any input 的本地化字符串。
        /// </summary>
        internal static string IllegalState_tried_dequeue {
            get {
                return ResourceManager.GetString("IllegalState_tried_dequeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cannot push to uninitialized substream 的本地化字符串。
        /// </summary>
        internal static string IllegalState_uninitialized_substream {
            get {
                return ResourceManager.GetString("IllegalState_uninitialized_substream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chunk must be pulled from shared buffer 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_Chunk_be_pulled {
            get {
                return ResourceManager.GetString("InvalidOperation_Chunk_be_pulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An empty module cannot be materialized (EmptyModule was given) 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_empty_module_cannot_be_mat {
            get {
                return ResourceManager.GetString("InvalidOperation_empty_module_cannot_be_mat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sink.First materialized on an empty stream 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_SinkFirst_empty_stream {
            get {
                return ResourceManager.GetString("InvalidOperation_SinkFirst_empty_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something went terribly wrong! 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_Something_wrong {
            get {
                return ResourceManager.GetString("InvalidOperation_Something_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The top level module cannot be materialized because it has unconnected ports 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_top_level_module {
            get {
                return ResourceManager.GetString("InvalidOperation_top_level_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not allowed to call AbsorbTermination() from OnDownstreamFinish. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_AbsorbTermination {
            get {
                return ResourceManager.GetString("NotSupported_AbsorbTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backpressure overflow strategy is not supported 的本地化字符串。
        /// </summary>
        internal static string NotSupported_Backpressure_strategy {
            get {
                return ResourceManager.GetString("NotSupported_Backpressure_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyModule cannot carry attributes 的本地化字符串。
        /// </summary>
        internal static string NotSupported_EmptyModule {
            get {
                return ResourceManager.GetString("NotSupported_EmptyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is invalid to combine materialized value with EmptyModule except with Keep.Left or Keep.Right 的本地化字符串。
        /// </summary>
        internal static string NotSupported_invalid_CMV {
            get {
                return ResourceManager.GetString("NotSupported_invalid_CMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO operation was successful. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_IO_operation {
            get {
                return ResourceManager.GetString("NotSupported_IO_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IteratorInterpreter does not support asynchronous events. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_IteratorInterpreter {
            get {
                return ResourceManager.GetString("NotSupported_IteratorInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoMaterializer cannot schedule a single event 的本地化字符串。
        /// </summary>
        internal static string NotSupported_NoMaterializer_event {
            get {
                return ResourceManager.GetString("NotSupported_NoMaterializer_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoMaterializer doesn&apos;t provide an ExecutionContext 的本地化字符串。
        /// </summary>
        internal static string NotSupported_NoMaterializer_excontext {
            get {
                return ResourceManager.GetString("NotSupported_NoMaterializer_excontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoMaterializer cannot materialize 的本地化字符串。
        /// </summary>
        internal static string NotSupported_NoMaterializer_materialize {
            get {
                return ResourceManager.GetString("NotSupported_NoMaterializer_materialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoMaterializer cannot be named 的本地化字符串。
        /// </summary>
        internal static string NotSupported_NoMaterializer_named {
            get {
                return ResourceManager.GetString("NotSupported_NoMaterializer_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoMaterializer cannot schedule a repeated event 的本地化字符串。
        /// </summary>
        internal static string NotSupported_NoMaterializer_repeatedevent {
            get {
                return ResourceManager.GetString("NotSupported_NoMaterializer_repeatedevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OverflowStrategy.Backpressure is not supported 的本地化字符串。
        /// </summary>
        internal static string NotSupported_OS_Backpressure {
            get {
                return ResourceManager.GetString("NotSupported_OS_Backpressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot replace the shape of empty module 的本地化字符串。
        /// </summary>
        internal static string NotSupported_replace_EmptyM {
            get {
                return ResourceManager.GetString("NotSupported_replace_EmptyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot replace the shape of a FlowModule 的本地化字符串。
        /// </summary>
        internal static string NotSupported_replace_shapeOfFM {
            get {
                return ResourceManager.GetString("NotSupported_replace_shapeOfFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cannot replace the shape of a Sink, you need to wrap it in a Graph for that 的本地化字符串。
        /// </summary>
        internal static string NotSupported_replace_shapeOfSink {
            get {
                return ResourceManager.GetString("NotSupported_replace_shapeOfSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cannot replace the shape of a Source, you need to wrap it in a Graph for that 的本地化字符串。
        /// </summary>
        internal static string NotSupported_replace_shapeOfSrc {
            get {
                return ResourceManager.GetString("NotSupported_replace_shapeOfSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This stream can only read 的本地化字符串。
        /// </summary>
        internal static string NotSupported_Stream_Only_R {
            get {
                return ResourceManager.GetString("NotSupported_Stream_Only_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This stream can only write 的本地化字符串。
        /// </summary>
        internal static string NotSupported_Stream_Only_W {
            get {
                return ResourceManager.GetString("NotSupported_Stream_Only_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is illegal to throw exceptions from cancel(), rule 3.15 的本地化字符串。
        /// </summary>
        internal static string SignalThrew_from_cancel {
            get {
                return ResourceManager.GetString("SignalThrew_from_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is illegal to throw exceptions from request(), rule 3.16 的本地化字符串。
        /// </summary>
        internal static string SignalThrew_from_request {
            get {
                return ResourceManager.GetString("SignalThrew_from_request", resourceCulture);
            }
        }
    }
}
