//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akka.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Akka.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Do not create actors using &apos;new&apos;, always create them using an ActorContext/System 的本地化字符串。
        /// </summary>
        internal static string ActorInitialization_Actor_Ctor {
            get {
                return ResourceManager.GetString("ActorInitialization_Actor_Ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception occurred while resolving ActorSelection 的本地化字符串。
        /// </summary>
        internal static string ActorNotFound_ActorSel_Exc {
            get {
                return ResourceManager.GetString("ActorNotFound_ActorSel_Exc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 subject was null 的本地化字符串。
        /// </summary>
        internal static string ActorNotFound_ActorSel_Sub {
            get {
                return ResourceManager.GetString("ActorNotFound_ActorSel_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxBackoff must be greater than MinBackoff 的本地化字符串。
        /// </summary>
        internal static string Argument_BackoffOptions_Max {
            get {
                return ResourceManager.GetString("Argument_BackoffOptions_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinBackoff must be greater than 0 的本地化字符串。
        /// </summary>
        internal static string Argument_BackoffOptions_Min {
            get {
                return ResourceManager.GetString("Argument_BackoffOptions_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RandomFactor must be between 0.0 and 1.0 的本地化字符串。
        /// </summary>
        internal static string Argument_BackoffOptions_Random {
            get {
                return ResourceManager.GetString("Argument_BackoffOptions_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The capacity for BoundedMailbox cannot be negative 的本地化字符串。
        /// </summary>
        internal static string Argument_BoundedMailbox_Capacity {
            get {
                return ResourceManager.GetString("Argument_BoundedMailbox_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The push time-out for BoundedMailbox cannot be be negative 的本地化字符串。
        /// </summary>
        internal static string Argument_BoundedMailbox_PushTimeout {
            get {
                return ResourceManager.GetString("Argument_BoundedMailbox_PushTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The capacity for BoundedMessageQueue can not be negative 的本地化字符串。
        /// </summary>
        internal static string Argument_BoundedMessageQueue {
            get {
                return ResourceManager.GetString("Argument_BoundedMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 virtualNodesFactor must be &gt;= 1 的本地化字符串。
        /// </summary>
        internal static string Argument_ConsistentHash_VirtualNodesFactor {
            get {
                return ResourceManager.GetString("Argument_ConsistentHash_VirtualNodesFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to resolve the target Provider 的本地化字符串。
        /// </summary>
        internal static string Argument_Futures_Ask {
            get {
                return ResourceManager.GetString("Argument_Futures_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The create function must be a &apos;new T (args)&apos; expression 的本地化字符串。
        /// </summary>
        internal static string Argument_PropsCreate {
            get {
                return ResourceManager.GetString("Argument_PropsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RouterConfig must be a Pool with defined resizer 的本地化字符串。
        /// </summary>
        internal static string Argument_ResizablePoolCell_Pool {
            get {
                return ResourceManager.GetString("Argument_ResizablePoolCell_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiler cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_Compiler {
            get {
                return ResourceManager.GetString("ArgumentNull_Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopyAndAdd cause exception cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_CopyAndAdd {
            get {
                return ResourceManager.GetString("ArgumentNull_CopyAndAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CopyAndRemove cause exception cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_CopyAndRemove {
            get {
                return ResourceManager.GetString("ArgumentNull_CopyAndRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeadLetter recipient may not be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_DeadLetterR {
            get {
                return ResourceManager.GetString("ArgumentNull_DeadLetterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeadLetter sender may not be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_DeadLetterS {
            get {
                return ResourceManager.GetString("ArgumentNull_DeadLetterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message cannot be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_EnvelopeMsg {
            get {
                return ResourceManager.GetString("ArgumentNull_EnvelopeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The subscriber cannot be a null actor. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_EsSubscriber {
            get {
                return ResourceManager.GetString("ArgumentNull_EsSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Producer cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_FastLazyProducer {
            get {
                return ResourceManager.GetString("ArgumentNull_FastLazyProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_FastLazyState {
            get {
                return ResourceManager.GetString("ArgumentNull_FastLazyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no mailbox owner or system given 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_LogMailbox {
            get {
                return ResourceManager.GetString("ArgumentNull_LogMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message to log must not be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_LogMessage {
            get {
                return ResourceManager.GetString("ArgumentNull_LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message formatter must not be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_LogMessageFormatter {
            get {
                return ResourceManager.GetString("ArgumentNull_LogMessageFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mapping cannot be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_Mapping {
            get {
                return ResourceManager.GetString("ArgumentNull_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuppressedDeadLetter recipient may not be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_SuppressedDeadLetterR {
            get {
                return ResourceManager.GetString("ArgumentNull_SuppressedDeadLetterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuppressedDeadLetter sender may not be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_SuppressedDeadLetterS {
            get {
                return ResourceManager.GetString("ArgumentNull_SuppressedDeadLetterS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type cannot be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_Type {
            get {
                return ResourceManager.GetString("ArgumentNull_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 message must not be null 的本地化字符串。
        /// </summary>
        internal static string ArgumentNull_WatchWithMsg {
            get {
                return ResourceManager.GetString("ArgumentNull_WatchWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must call StartWith before calling Initialize. 的本地化字符串。
        /// </summary>
        internal static string IllegalState_FSM_Initialize {
            get {
                return ResourceManager.GetString("IllegalState_FSM_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must call StartWith before calling StateData. 的本地化字符串。
        /// </summary>
        internal static string IllegalState_FSM_StateData {
            get {
                return ResourceManager.GetString("IllegalState_FSM_StateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must call StartWith before calling StateName. 的本地化字符串。
        /// </summary>
        internal static string IllegalState_FSM_StateName {
            get {
                return ResourceManager.GetString("IllegalState_FSM_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 initialize called more than once! 的本地化字符串。
        /// </summary>
        internal static string IllegalState_RepointableActorRef_Initialize {
            get {
                return ResourceManager.GetString("IllegalState_RepointableActorRef_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsStarted called before initialized 的本地化字符串。
        /// </summary>
        internal static string IllegalState_RepointableActorRef_IsStarted {
            get {
                return ResourceManager.GetString("IllegalState_RepointableActorRef_IsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underlying cell is null 的本地化字符串。
        /// </summary>
        internal static string IllegalState_RepointableActorRef_Underlying {
            get {
                return ResourceManager.GetString("IllegalState_RepointableActorRef_Underlying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actor name must not be empty. 的本地化字符串。
        /// </summary>
        internal static string InvalidActorName_Empty {
            get {
                return ResourceManager.GetString("InvalidActorName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actor name must not be null. 的本地化字符串。
        /// </summary>
        internal static string InvalidActorName_Null {
            get {
                return ResourceManager.GetString("InvalidActorName_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message is null 的本地化字符串。
        /// </summary>
        internal static string InvalidMessage_MsgIsNull {
            get {
                return ResourceManager.GetString("InvalidMessage_MsgIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create child while terminating or terminated 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_ActorCell_IsTerminating {
            get {
                return ResourceManager.GetString("InvalidOperation_ActorCell_IsTerminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot RegisterTempActor() with anything not obtained from tempPath() 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_ActorRefProvider_Reg {
            get {
                return ResourceManager.GetString("InvalidOperation_ActorRefProvider_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot UnregisterTempActor() with anything not obtained from tempPath() 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_ActorRefProvider_Unreg {
            get {
                return ResourceManager.GetString("InvalidOperation_ActorRefProvider_Unreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ActorSystem already terminated. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_ActorSystem_AlreadyTerminated {
            get {
                return ResourceManager.GetString("InvalidOperation_ActorSystem_AlreadyTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunTask must be called from an actor context. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_ActorTaskScheduler_RunTask {
            get {
                return ResourceManager.GetString("InvalidOperation_ActorTaskScheduler_RunTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextStateData is only available during OnTransition 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_FSM_NextStateData {
            get {
                return ResourceManager.GetString("InvalidOperation_FSM_NextStateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The partial action has been built. No handler can be added after that. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_MatchBuilder_Built {
            get {
                return ResourceManager.GetString("InvalidOperation_MatchBuilder_Built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A handler that catches all messages has been added. No handler can be added after that. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_MatchBuilder_MatchAnyAdded {
            get {
                return ResourceManager.GetString("InvalidOperation_MatchBuilder_MatchAnyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You may only call Receive-methods when constructing the actor and inside Become(). 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_ReceiveActor_Ensure {
            get {
                return ResourceManager.GetString("InvalidOperation_ReceiveActor_Ensure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolver is not initialized 的本地化字符串。
        /// </summary>
        internal static string InvalidOperation_Resolve_Produce {
            get {
                return ResourceManager.GetString("InvalidOperation_Resolve_Produce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no active ActorContext, this is most likely due to use of async operations from within this actor. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_Actor_Context {
            get {
                return ResourceManager.GetString("NotSupported_Actor_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RootActorPath must have undefined Uid 的本地化字符串。
        /// </summary>
        internal static string NotSupported_ActorPath_Uid {
            get {
                return ResourceManager.GetString("NotSupported_ActorPath_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not serialize LocalOnlyDecider 的本地化字符串。
        /// </summary>
        internal static string NotSupported_Can_Not_Serialize_LocalOnlyDecider {
            get {
                return ResourceManager.GetString("NotSupported_Can_Not_Serialize_LocalOnlyDecider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object to convert is not a byte array. 的本地化字符串。
        /// </summary>
        internal static string NotSupported_IsNotByteArray {
            get {
                return ResourceManager.GetString("NotSupported_IsNotByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bug, we should not get here 的本地化字符串。
        /// </summary>
        internal static string NotSupported_LocalActorRef_Bug {
            get {
                return ResourceManager.GetString("NotSupported_LocalActorRef_Bug", resourceCulture);
            }
        }
    }
}
